version: "3.9"

volumes:
  # Nombres FIJOS para que sea fácil limpiar/respaldar
  seafile_db_prod:
  seafile_data_prod:

services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_LOG_CONSOLE=true
      - MARIADB_AUTO_UPGRADE=1
      - TZ=${TIMEZONE}
    volumes:
      - seafile_db_prod:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -p$$MYSQL_ROOT_PASSWORD -h 127.0.0.1 --silent"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks:
      default: {}
      monitoring:
        aliases:
          - seafile-db

  memcached:
    image: memcached:1.6
    restart: unless-stopped
    entrypoint: memcached -m 256

  seafile:
    image: seafileltd/seafile-mc:9.0.10
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      memcached:
        condition: service_started
    environment:
      # ---- DB host/root ----
      - DB_HOST=db
      - DB_ROOT_PASSWD=${DB_ROOT_PASSWD}
      - DB_USER=${SEAFILE_DB_USER}
      - DB_PASSWD=${SEAFILE_DB_PASS}

      # ---- Bases de datos ----
      - CCNET_DB=ccnet_db
      - SEAFILE_DB=seafile_server
      - SEAHUB_DB=seahub_server

      # ---- Host/URLs/admin ----
      - TIME_ZONE=${TIMEZONE}
      - SEAFILE_SERVER_HOSTNAME=${DOMAIN}
      - SEAFILE_SERVER_PROTOCOL=https
      - SEAFILE_SERVER_LETSENCRYPT=false
      - SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN_EMAIL}
      - SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD}
    volumes:
      - seafile_data_prod:/shared
      - ./seafile/conf:/shared/seafile/conf
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 5

  onlyoffice:
    image: onlyoffice/documentserver:latest
    restart: unless-stopped
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=${ONLYOFFICE_JWT_SECRET}
      - TZ=${TIMEZONE}
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost/healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 5

  nginx:
    image: ghcr.io/nellymg09/seafile-nginx:latest
    restart: unless-stopped
    depends_on:
      - seafile
      - onlyoffice
    ports:
      - "9455:9455"   # Seafile (HTTPS terminado en Nginx)
      - "9458:9458"   # OnlyOffice (HTTPS terminado en Nginx)
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/logs:/var/log/nginx
    healthcheck:
      test: ["CMD-SHELL", "curl -fk https://127.0.0.1:9455/ >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      
networks:
  monitoring:
    external: true
    name: grafana-stack_monitoring
